# Generated by Django 4.2.4 on 2023-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
