# Generated by Django 4.2.4 on 2023-08-14 12:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_workslot_is_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='workslot',
            name='overtime',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workslot',
            name='overtime_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
