# Generated by Django 4.2.4 on 2023-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workslot',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
