# Generated by Django 4.2.4 on 2023-09-16 10:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_workslot_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workslot',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
