# Generated by Django 4.2.4 on 2023-08-14 12:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_overtime_factor_workslot_overtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workslot',
            name='overtime',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
