# Generated by Django 4.2.4 on 2023-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_workslot_break_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workslot',
            name='payment_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
