# Generated by Django 4.2.4 on 2023-08-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_workslot_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workslot',
            name='is_paid',
        ),
    ]
