# Generated by Django 4.2.4 on 2023-08-19 17:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_workslot_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('normal_working_hours', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.site'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.site'),
        ),
        migrations.AlterField(
            model_name='workslot',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workslot',
            name='overtime',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='workslot',
            name='overtime_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employee',
            name='label',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.employeelabel'),
            preserve_default=False,
        ),
    ]
