# Generated by Django 4.2.4 on 2023-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeelabel_alter_employee_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=12),
        ),
    ]
